Cleanup
AlkaMotors/AM32-MultiRotor-ESC-firmware pull request #56
Opened 2021-08-03 13:25 UTC by giacomo892

Substitute #55 . PR to master this time

2021-08-04 00:27 UTC, DusKing1 approved these changes

2021-08-05 05:23 UTC, giacomo892 commented
Hi @AlkaMotors can this be merged?

2021-08-06 17:23 UTC, AlkaMotors commented
Sorry i didn't get a chance to really look it over. It looks like all the comments for other input types are removed?  I see lots of line changed where nothing appears to be changed at all?

2021-08-07 07:14 UTC, giacomo892 commented
@AlkaMotors yeah and those are removing of white space at the end of the line

2021-08-07 07:31 UTC, cruwaller commented
> @AlkaMotors yeah and those are removing of white space at the end of the line

you also removed newlines at the end of the files. You should keep those.

2021-08-07 08:02 UTC, giacomo892 commented
> > @AlkaMotors yeah and those are removing of white space at the end of the line
> 
> you also removed newlines at the end of the files. You should keep those.

Can you point out where I did it? Cannot see it

2021-08-07 08:07 UTC, cruwaller requested changes
@AlkaMotors to decide if he wants to keep the commented protocols just in case.
These changes are quite minor things after all...

2021-08-07 08:07 UTC, cruwaller commented on Src/dshot.c
> +}
Keep new line

2021-08-07 08:07 UTC, cruwaller commented on Src/phaseouts.c
> +}
Keep new line

2021-08-07 08:07 UTC, cruwaller commented on Src/signal.c
> +}
Keep new line

2021-08-07 08:07 UTC, cruwaller commented on Src/sounds.c
> +}
Keep new line

2021-08-07 08:18 UTC, giacomo892 commented
@cruwaller Done. The code needs mayor cleanup, we should start from something :)

2021-08-07 14:12 UTC, merged

2021-08-07 14:12 UTC, AlkaMotors commented
I agree...  It does need cleanup, in small steps so I can understand it!   The code for those protocols are gone so we can get rid of the commented lines now.